services:
  migrate:
    image: migrate/migrate
    volumes:
      - ./go_app/migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
      - "up"

  go_app:
    image: ghcr.io/bohdanberebel/portfolio-go:latest
    environment:
      PORT: 8080
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GIN_MODE: release
    expose:
      - "8080"
    depends_on:
      migrate:
        condition: service_completed_successfully

  python_app:
    image: ghcr.io/bohdanberebel/portfolio-python:latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "8000"
    depends_on:
      migrate:
        condition: service_completed_successfully

  frontend:
    image: ghcr.io/bohdanberebel/portfolio-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - go_app
      - python_app
