events {}

http {

  server {
    listen 80;

    # GO service
    location /api/go/ {
      proxy_pass http://go_app:8080/;
    }

    # PYTHON service
    location /api/py/ {
      proxy_pass http://python_app:8000/;
    }
  }
}